FROM ubuntu:14.04
MAINTAINER Ricardo Moraleida

RUN apt-get update
RUN apt-get -y install imagemagick \
		subversion \
		git-core \
		zip \
		unzip \
		ngrep \
		curl \
		make \
		vim \
		colordiff \
		postfix \
		ntp \
		gettext \
		graphviz \
		dos2unix \
		libsqlite3-dev